# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/x/git/chester

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/x/git/chester

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/x/git/chester/CMakeFiles /home/x/git/chester/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/x/git/chester/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CHESTER

# Build rule for target.
CHESTER: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CHESTER
.PHONY : CHESTER

# fast build rule for target.
CHESTER/fast:
	$(MAKE) -f CMakeFiles/CHESTER.dir/build.make CMakeFiles/CHESTER.dir/build
.PHONY : CHESTER/fast

chester.o: chester.c.o
.PHONY : chester.o

# target to build an object file
chester.c.o:
	$(MAKE) -f CMakeFiles/CHESTER.dir/build.make CMakeFiles/CHESTER.dir/chester.c.o
.PHONY : chester.c.o

chester.i: chester.c.i
.PHONY : chester.i

# target to preprocess a source file
chester.c.i:
	$(MAKE) -f CMakeFiles/CHESTER.dir/build.make CMakeFiles/CHESTER.dir/chester.c.i
.PHONY : chester.c.i

chester.s: chester.c.s
.PHONY : chester.s

# target to generate assembly for a file
chester.c.s:
	$(MAKE) -f CMakeFiles/CHESTER.dir/build.make CMakeFiles/CHESTER.dir/chester.c.s
.PHONY : chester.c.s

common.o: common.c.o
.PHONY : common.o

# target to build an object file
common.c.o:
	$(MAKE) -f CMakeFiles/CHESTER.dir/build.make CMakeFiles/CHESTER.dir/common.c.o
.PHONY : common.c.o

common.i: common.c.i
.PHONY : common.i

# target to preprocess a source file
common.c.i:
	$(MAKE) -f CMakeFiles/CHESTER.dir/build.make CMakeFiles/CHESTER.dir/common.c.i
.PHONY : common.c.i

common.s: common.c.s
.PHONY : common.s

# target to generate assembly for a file
common.c.s:
	$(MAKE) -f CMakeFiles/CHESTER.dir/build.make CMakeFiles/CHESTER.dir/common.c.s
.PHONY : common.c.s

mem.o: mem.c.o
.PHONY : mem.o

# target to build an object file
mem.c.o:
	$(MAKE) -f CMakeFiles/CHESTER.dir/build.make CMakeFiles/CHESTER.dir/mem.c.o
.PHONY : mem.c.o

mem.i: mem.c.i
.PHONY : mem.i

# target to preprocess a source file
mem.c.i:
	$(MAKE) -f CMakeFiles/CHESTER.dir/build.make CMakeFiles/CHESTER.dir/mem.c.i
.PHONY : mem.c.i

mem.s: mem.c.s
.PHONY : mem.s

# target to generate assembly for a file
mem.c.s:
	$(MAKE) -f CMakeFiles/CHESTER.dir/build.make CMakeFiles/CHESTER.dir/mem.c.s
.PHONY : mem.c.s

model.o: model.c.o
.PHONY : model.o

# target to build an object file
model.c.o:
	$(MAKE) -f CMakeFiles/CHESTER.dir/build.make CMakeFiles/CHESTER.dir/model.c.o
.PHONY : model.c.o

model.i: model.c.i
.PHONY : model.i

# target to preprocess a source file
model.c.i:
	$(MAKE) -f CMakeFiles/CHESTER.dir/build.make CMakeFiles/CHESTER.dir/model.c.i
.PHONY : model.c.i

model.s: model.c.s
.PHONY : model.s

# target to generate assembly for a file
model.c.s:
	$(MAKE) -f CMakeFiles/CHESTER.dir/build.make CMakeFiles/CHESTER.dir/model.c.s
.PHONY : model.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... CHESTER"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... chester.o"
	@echo "... chester.i"
	@echo "... chester.s"
	@echo "... common.o"
	@echo "... common.i"
	@echo "... common.s"
	@echo "... mem.o"
	@echo "... mem.i"
	@echo "... mem.s"
	@echo "... model.o"
	@echo "... model.i"
	@echo "... model.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

