#include "msg.h"
#include <stdio.h>
#include <stdlib.h>

void PrintMenuMap(void){
  fprintf(stderr, "                                                         \n");
  fprintf(stderr, "Usage: CHESTER-map <OPTIONS>... [FILE]:<...> [FILE]:<...>\n");
  fprintf(stderr, "CHESTER-map: a tool to map relative singularity regions  \n");
  fprintf(stderr, "The (probabilistic) Bloom filter is automatically set.   \n");
  fprintf(stderr, "                                                         \n");
  fprintf(stderr, "  -v                       verbose mode,                 \n");
  fprintf(stderr, "  -a                       about CHESTER,                \n");
  fprintf(stderr, "  -s <value>               bloom size,                   \n");
  fprintf(stderr, "  -i                       use inversions,               \n");
  fprintf(stderr, "  -p                       show positions/words,         \n");
  fprintf(stderr, "  -k <value>               k-mer size (up to 30),        \n");
  fprintf(stderr, "                                                         \n");
  fprintf(stderr, "  [rFile1]:<rFile2>:<...>  reference file(s),            \n");
  fprintf(stderr, "  [tFile1]:<tFile2>:<...>  target file(s).               \n");
  fprintf(stderr, "                                                         \n");
  fprintf(stderr, "The reference files may be FASTA, FASTQ or DNA SEQ,      \n");
  fprintf(stderr, "while the target files may be FASTA OR DNA SEQ.          \n");
  fprintf(stderr, "Report bugs to <{pratas,raquelsilva,ap,pjf}@ua.pt>.      \n");
  fprintf(stderr, "                                                         \n");
  }

void PrintMenuFilter(void){
  fprintf(stderr, "                                                     \n");
  fprintf(stderr, "Usage: CHESTER-filter <OPTIONS>... [FILE]:<...>      \n");
  fprintf(stderr, "CHESTER-filter: a tool to filter maps (CHESTER-map)  \n");
  fprintf(stderr, "                                                     \n");
  fprintf(stderr, "  -v                       verbose mode,             \n");
  fprintf(stderr, "  -a                       about CHESTER,            \n");
  fprintf(stderr, "  -t <value>               threshold [0.0;1.0],      \n");
  fprintf(stderr, "  -w <value>               window size,              \n");
  fprintf(stderr, "  -u <value>               sub-sampling,             \n");
  fprintf(stderr, "                                                     \n");
  fprintf(stderr, "  [tFile1]:<tFile2>:<...>  target file(s).           \n");
  fprintf(stderr, "                                                     \n");
  fprintf(stderr, "The target files may be generated by CHESTER-map.    \n");
  fprintf(stderr, "Report bugs to <{pratas,raquelsilva,ap,pjf}@ua.pt>.  \n");
  fprintf(stderr, "                                                     \n");
  }

void PrintMenuVisual(void){
  fprintf(stderr, "                                                     \n");
  fprintf(stderr, "Usage: CHESTER-visual <OPTIONS>... [FILE]:<...>\n");
  fprintf(stderr, "CHESTER-visual: visualize relative singularity regions.\n");
  fprintf(stderr, "                                                     \n");
  fprintf(stderr, "  -v                       verbose mode,             \n");
  fprintf(stderr, "  -a                       about CHESTER,            \n");
  fprintf(stderr, "  -e <value>               enlarge painted regions,  \n");
  fprintf(stderr, "                                                     \n");
  fprintf(stderr, "  [tFile1]:<tFile2>:<...>  target file(s).           \n");
  fprintf(stderr, "                                                     \n");
  fprintf(stderr, "Report bugs to <{pratas,raquelsilva,ap,pjf}@ua.pt>.  \n");
  fprintf(stderr, "                                                     \n");
  }

void PrintVersion(void){
  fprintf(stderr,
    "                                                                       \n"
    "                          ===================                          \n"
    "                          |   CHESTER %u.%u   |                        \n"
    "                          ===================                          \n"
    "                                                                       \n"
    "               A probabilistic tool to map and visualize               \n"
    "                     relative singularity regions.                     \n"
    "                                                                       \n"
    "              Copyright (C) 2015-2018 University of Aveiro.            \n"
    "                                                                       \n"
    "                  This is a Free software, under GPLv3.                \n"
    "                                                                       \n"
    "You may redistribute copies of it under the terms of the GNU - General \n"
    "Public License v3 <http://www.gnu.org/licenses/gpl.html>. There is NOT \n"
    "ANY WARRANTY, to the extent permitted by law. Developed and Written by \n"
    "                                                                       \n"
    "                     Diogo Pratas, Raquel M. Silva,                    \n"
    "              Armando J. Pinho and Paulo J. S. G. Ferreira.            \n"
    "                                                                       \n",
    VERSION, RELEASE);
  }

